function        out             = mv2_doPIMs(i1,fbc);
%% generated by mv2_i2m on 19-Apr-2022 10:55:01
% source file: iv2_doPIMs
% 
if isnumeric(i1);               feval(['local_f',intstr(i1(1),3)],fbc);
else;                           out                         = feval(['local_',i1],fbc);             end;
return;
%
function        out             = local_opt(fbc);
%% listing option strings of this i-file:
% 
% 
out                             = [
'v4t'
'ifc'
'cpt'
'ipj'
'pmp'
'eza'
'avr'
'snu'];
return;
%% 
function        out             = local_fun(fbc);
%% returning step descriptions
% 
out{1}                          = 'Complete/revise/review Analysis Sets (PIMs)';
out{2}                          = 'Perform plasma input methods (PIMs)';
out{3}                          = 'display & plot PIM results';
out{4}                          = 'Select maps to generate (PIMs)';
out{5}                          = 'generate functional maps';
out{6}                          = 'view functional maps in MRI space';
out{7}                          = 'view spatially normalized & smoothed maps';
out{8}                          = 'display map completion status across subjects/scans';
return;
%% 
function        out             = local_fls(fbc);
%% List of input/output files:
% 
global g4iv2;
out                             = {
g4iv2.xxx(fbc(3)).v4t
['mpe/p4PIMs_',g4iv2.xxx(fbc(3)).eza,'.mat']
['mpe/r4PIMs_',g4iv2.xxx(fbc(3)).eza,'_',g4iv2.xxx(fbc(3)).cpt,'.mat']
['res/',g4iv2.xxx(fbc(3)).ifc,'_',g4iv2.xxx(fbc(3)).eza,'.eza']
['res/',g4iv2.xxx(fbc(3)).ifc,'_',g4iv2.xxx(fbc(3)).eza,'_ok.txt']
['pet/',g4iv2.xxx(fbc(3)).cpt,'.cpt']
['pet/',g4iv2.xxx(fbc(3)).cpt,'_ok.txt']
['res/',g4iv2.xxx(fbc(3)).ifc,'_',g4iv2.xxx(fbc(3)).eza,'_',g4iv2.xxx(fbc(3)).cpt,'_PIMs_done.m']
['mpe/p4PIMs_',g4iv2.xxx(fbc(3)).eza,'_maps_',g4iv2.xxx(fbc(3)).cpt,'_',g4iv2.xxx(fbc(3)).snu,'.mat']
['pet/',g4iv2.xxx(fbc(3)).ifc,'.ezm']
['ezr/',g4iv2.xxx(fbc(3)).ipj,'_',g4iv2.xxx(fbc(3)).ifc,'_',g4iv2.xxx(fbc(3)).pmp,'_',g4iv2.xxx(fbc(3)).avr,'_p2m.mat']
['ezr/',g4iv2.xxx(fbc(3)).pmp,'_m2m.mat']
['res/p4PIMs_',g4iv2.xxx(fbc(3)).eza,'_maps_',g4iv2.xxx(fbc(3)).cpt,'_done.m']
['mpe/q4PIMs_',g4iv2.xxx(fbc(3)).eza,'_maps_',g4iv2.xxx(fbc(3)).cpt,'_',g4iv2.xxx(fbc(3)).snu,'.mat']};
%
return;
%% 
function        out             = local_fns(fbc);
%% [in/out, file#@process, process#, file#@ifile, taskID#]
% 
out                             = [
1    1    1    1  109
2    1    1    2  109
2    2    1    3  109
1    1    2    4  115
1    2    2    5  115
1    3    2    3  115
1    4    2    6  115
1    5    2    7  115
2    1    2    8  115
1    1    3    3  111
1    1    4    3  100
2    1    4    9  100
1    1    5   10  115
1    2    5    4  115
1    3    5    9  115
1    4    5    5  115
1    5    5   11  115
1    6    5   12  115
1    7    5    6  115
2    1    5   13  115
2    2    5   14  115
1    1    6   14  111
1    2    6   13  111
1    1    7   14  111
1    1    8   14  111];
return;
%% 
function                        local_f001(fbc);
%% command lines for step 1
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_s2m('pims',fbc(1),iii{1},   ooo);                  
return
%% 
function                        local_f002(fbc);
%% command lines for step 2
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_performPIMs(iii{1},iii{4},iii{3},   ooo,fbc,0);    
return
%% 
function                        local_f003(fbc);
%% command lines for step 3
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
x                               = load(iii{1});        
x.fbc                           = fbc(1,    1:3);      
x.job                           = 'disp_res';          
mv2_dispRes('set',x);                                  
return
%% 
function                        local_f004(fbc);
%% command lines for step 4
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_genMaps(iii,[fbc,1],ooo);                          
return
%% 
function                        local_f005(fbc);
%% command lines for step 5
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_genMaps(iii,[fbc,2],ooo);                          
return
%% 
function                        local_f006(fbc);
%% command lines for step 6
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_genMaps(iii,[fbc,3],[]);                           
return
%% 
function                        local_f007(fbc);
%% command lines for step 7
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_genMaps(iii,[fbc,4],[]);                           
return
%% 
function                        local_f008(fbc);
%% command lines for step 8
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_genMaps(iii,[fbc,11],ooo);                         
return
%% 
