function        out             = mv2_muse(i1,fbc);
%% generated by mv2_i2m on 25-Feb-2023 17:49:57
% source file: C:\Users\junhua\Desktop\MUSE&DEPENDENCIES\iv2_jm_MUSE\iv2_muse.m
% 
if isnumeric(i1);               feval(['local_f',intstr(i1(1),3)],fbc);
else;                           out                         = feval(['local_',i1],fbc);             end;
return;
%
function        out             = local_opt(fbc);
%% listing option strings of this i-file:
% 
% 
out                             = [
'pmp'];
return;
%% 
function        out             = local_fun(fbc);
%% returning step descriptions
% 
out{1}                          = 'review original MRI, if avaiable';
out{2}                          = 'outsource MUSE ROI segmentation, complete when MUSE completed';
out{3}                          = 'define ACPC points on the MUSE input MRI';
out{4}                          = 'crop MUSE outputs around the brain';
out{5}                          = 'plot left vs. right VOI volumes';
out{6}                          = 'review/approve gray matter segmentation of MUSE';
return;
%% 
function        out             = local_fls(fbc);
%% List of input/output files:
% 
global g4iv2;
out                             = {
'mri/tmp.mri'
'mri/muse_input.nii'
'mri/muse_output.nii'
'mri/muse_input_copy.nii'
'ezr/muse_input.acpc'
'mri/muse_msbc_museset.nii'
'mri/muse_msbc.nii'
'mri/muse_mssz.nii'
'mri/muse_msbc_BOLs.xyz'
'mri/muse_msbc_museset.ezr'
['ezr/',g4iv2.xxx(fbc(3)).pmp,'_m2m.mat']
'ezr/muse_msbc_BOLs_ok.txt'};
%
return;
%% 
function        out             = local_fns(fbc);
%% [in/out, file#@process, process#, file#@ifile, taskID#]
% 
out                             = [
1    1    1    1  111
1    1    2    2  105
2    1    2    3  105
2    2    2    4  105
1    1    3    2  105
2    1    3    5  105
1   1   4   3  97
1   2   4   2  97
1   3   4   4  97
1   4   4   5  97
2   1   4   6  97
2   2   4   7  97
2   3   4   8  97
2   4   4   9  97
2   5   4  10  97
2   6   4  11  97
1    1    5   10  111
1   1   6   7  99
1   2   6   9  99
1   3   6  11  99
2   1   6  12  99];
return;
%% 
function                        local_f001(fbc);
%% command lines for step 1
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
[idx, inm]                      = fileparts(iii{1});                                                        
if exist(fullfile(idx, [inm,'.nii']),'file');                                                               
    vL2Land(fullfile(idx, [inm,'.nii']), 'fun','disp');                                                     
else;                                                                                                       
    disp('.problem! original MRI in .nii format - not ready');                                      end;    
return
%% 
function                        local_f002(fbc);
%% command lines for step 2
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
copyfile(iii{1},ooo{2},'f');                                                                                
[idx, inm]                      = fileparts(iii{1});                                                        
disp('MUSE work finished')                                                                                  
return
%% 
function                        local_f003(fbc);
%% command lines for step 3
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
v0                              = spm_vol(iii{1});                                                          
h                               = findobj(findobj(groot,'Tag','iv2L2W'), 'Tag','L2W_gUseR0');               
str                             = get(h,    'String');                                                      
bgc                             = get(h,    'BackgroundColor');                                             
set(h,  'String','Starting VOILand. Be patient ..', 'BackgroundColor',iv2_bgcs(11));                        
drawnow;                                                                                                    
vL2Land(iii{1}, 'fun','acpc',   'vfl',ooo{1},   'mnt',whichMonitor([]));                                    
set(h,  'String',str,   'BackgroundColor',bgc);                                                             
vL2_BJs('Zoom',1);                                                                                          
vL2_BJs('Zoom',1);                                                                                          
drawnow;                                                                                                    
global g4vL2;                                                                                               
g4vL2{double(gcf)}.exit_do      = ['figure(findobj(groot,''Tag'',''iv2L2W'')); ', ...                       
    	'set(gcf, ''CurrentObject'',findobj(gcf, ''String'',''Update'')); mv2_a2([]);'];                       
return
%% 
function                        local_f004(fbc);
%% command lines for step 4
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
if fbc(3)>1;                                                                            return;         end;
cropMR_muse(iii,ooo);                                                                                       
if exist(ooo{2},'file');        mv2_w4MMcoreg('run',fbc(1, 1:3),ooo(2),ooo(6));                         end;
return
%% 
function                        local_f005(fbc);
%% command lines for step 5
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_run_MUSE('plot_lr_voi_volumes',iii,fbc(1, 1:3));                                                        
return
%% 
function                        local_f006(fbc);
%% command lines for step 6
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
iii{end+1}                     	= 'FS';                                                                     
mv2_w4MMcoreg('ols',fbc,        iii,ooo);                                                                   
return
%% 
