function        out             = mv2_FS1st(i1,fbc);
%% generated by mv2_i2m on 09-Aug-2022 09:40:06
% source file: iv2_FS1st
% 
if isnumeric(i1);               feval(['local_f',intstr(i1(1),3)],fbc);
else;                           out                         = feval(['local_',i1],fbc);             end;
return;
%
function        out             = local_opt(fbc);
%% listing option strings of this i-file:
% 
% 
out                             = [
'pmp'];
return;
%% 
function        out             = local_fun(fbc);
%% returning step descriptions
% 
out{1}                          = 'review original MRI, if avaiable';
out{2}                          = 'generate scripts to run MUSE or Freesurfer (FS)';
out{3}                          = 'reformat FS-derived MRI (.mgz > .nii)';
out{4}                          = 'define ACPC points on FS-derived MRI';
out{5}                          = 'crop FS outputs around the brain';
out{6}                          = 'plot left vs. right VOI volumes';
out{7}                          = 'review/approve gray matter segmentation of FS';
out{8}                          = 'activate correction routine for Freesurfer outputs (privileged users only)';
return;
%% 
function        out             = local_fls(fbc);
%% List of input/output files:
% 
global g4iv2;
out                             = {
'mri\tmp.mri'
'mri\fs_submitted.txt'
'mri\tmp_aparc_aseg.nii'
'mri\mgz_done.txt'
'mri\mgz_bc0.nii'
'mri\mgz_bc0_osz.nii'
'ezr\mgz_bc0_osz.acpc'
'mri\mgz_bc1.nii'
'mri\fsbc_fs81.nii'
'mri\fsbc.nii'
'mri\fssz.nii'
'mri\fsbc_BOLs.xyz'
'mri\fsbc_fs81.ezr'
'mri\fsbc_fs45.ezr'
['ezr\',g4iv2.xxx(fbc(3)).pmp,'_m2m.mat']
'ezr\fsbc_BOLs_ok.txt'
['iv2\',g4iv2.xxx(fbc(3)).pmp,'_iv2_FS1st_rev_added.txt']};
%
return;
%% 
function        out             = local_fns(fbc);
%% [in/out, file#@process, process#, file#@ifile, taskID#]
% 
out                             = [
1    1    1    1  111
1    1    2    1  105
2    1    2    2  105
2    2    2    3  105
1   1   3   4  97
1   2   3   5  97
2   1   3   6  97
1    1    4    6  105
2    1    4    7  105
1   1   5   3  97
1   2   5   8  97
1   3   5   5  97
1   4   5   7  97
2   1   5   9  97
2   2   5  10  97
2   3   5  11  97
2   4   5  12  97
2   5   5  13  97
2   6   5  14  97
2   7   5  15  97
1    1    6   13  111
1   1   7  10  99
1   2   7  12  99
1   3   7  15  99
2   1   7  16  99
1    1    8    9  100
2    1    8   17  100];
return;
%% 
function                        local_f001(fbc);
%% command lines for step 1
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
[idx, inm]                      = fileparts(iii{1});                                                        
if exist(fullfile(idx, [inm,'.nii']),'file');                                                               
    vL2Land(fullfile(idx, [inm,'.nii']), 'fun','disp');                                                     
else;                                                                                                       
    disp('.problem! original MRI in .nii format - not ready');                                      end;    
return
%% 
function                        local_f002(fbc);
%% command lines for step 2
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
iii{2}                          = '';                                                                       
iii{3}                          = fbc(1, 1:3);                                                              
mv2_run_FS('single_script',iii,ooo);                                                                        
return
%% 
function                        local_f003(fbc);
%% command lines for step 3
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
if fbc(3)>1;                                                                       	return;         end;    
fs_cropMRIs(iii(2),'MRI',ooo,'mgz2nii');                                                                    
return
%% 
function                        local_f004(fbc);
%% command lines for step 4
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
v0                              = spm_vol(iii{1});                                                          
h                               = findobj(findobj(groot,'Tag','iv2L2W'), 'Tag','L2W_gUseR0');               
str                             = get(h,    'String');                                                      
bgc                             = get(h,    'BackgroundColor');                                             
set(h,  'String','Starting VOILand. Be patient ..', 'BackgroundColor',iv2_bgcs(11));                        
drawnow;                                                                                                    
vL2Land(iii{1}, 'fun','acpc',   'vfl',ooo{1},   'mnt',whichMonitor([]));                                    
set(h,  'String',str,   'BackgroundColor',bgc);                                                             
vL2_BJs('Zoom',1);                                                                                          
vL2_BJs('Zoom',1);                                                                                          
drawnow;                                                                                                    
global g4vL2;                                                                                               
g4vL2{double(gcf)}.exit_do      = ['figure(findobj(groot,''Tag'',''iv2L2W'')); ', ...                       
    	'set(gcf, ''CurrentObject'',findobj(gcf, ''String'',''Update'')); mv2_a2([]);'];                       
return
%% 
function                        local_f005(fbc);
%% command lines for step 5
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
if fbc(3)>1;                                                                            return;         end;
use_freeSurfer(831,iii,ooo);                                                                                
if exist(ooo{2},'file');        mv2_w4MMcoreg('run',fbc(1, 1:3),ooo(2),ooo(7));                         end;
return
%% 
function                        local_f006(fbc);
%% command lines for step 6
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_run_FS('plot_lr_voi_volumes',iii,fbc(1, 1:3));                                                          
return
%% 
function                        local_f007(fbc);
%% command lines for step 7
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
iii{end+1}                     	= 'FS';                                                                     
mv2_w4MMcoreg('ols',fbc,        iii,ooo);                                                                   
return
%% 
function                        local_f008(fbc);
%% command lines for step 8
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
p_use                           = feval(g4iv2.yyy.lds,    'manager',[]);                                    
if strcmpi(feval(g4iv2.yyy.lds,    'manager',[]), g4iv2.yyy.usr);                                           
    mv2_run_FS('add_iv2_fs1st_rev',{g4iv2.yyy.fpipk},ooo);                                                  
else;                           disp(['.problem! not a privileged user: ',g4iv2.yyy.usr]);              end;
return
%% 
