function    vL2_infoB(i1,i2); 

% To display (control) info-board of vL2Land 
%       
%       usage:      vL2_infoB('kind','what')
%       
% Current inputs:
%   kind -  gen,c10,info
%   what -  depends (on kind) see inside
% 
% (cL)2017    hkuwaba1@jhmi.edu 

margin                          = 2;
if nargin<margin;               help(mfilename);                                    return;         end;


h                               = findobj(gcf,  'Tag','vL2InfoB');
if isempty(h);                                                                      return;         end;
feval(['local_',lower(i1)],     h,i2);
return;
%%

function                        local_info(h,i2);
%%
imax                            = 6;
if ischar(i2);
    i1                          = umo_cstrs(char('saved','novois','nolabel','no2save','voi+',   ...
                                                            'nochanges'),lower(i2),  'im1');
    if ~i1;                     disp(['.error! wrong input 2: ',i2]);               return;         end;
else;                           i1                          = i2(1);                                end;
%                                
if i1==1;
% saved ..
	global g4vL2
    [idx, inm, iex]             = fileparts(g4vL2{double(gcf)}.vfl);
    set(h,  'String',           {' ',[' VOIs are saved to the designated file (info)'],' ',     ...
                                [' file: ',inm,iex],       ['   in: ',idx], ' Safe to exit'});
elseif i1==2;
    set(h,  'String',           {' ',' No VOI voxels (info)',  ' ',                             ...
                                '  Set the VOI label (''start a VOI'' GUI) and define it first',...
                                '  Use ''Info'' GUI to learn how to define/refine VOIs.'});
elseif i1==3;
    set(h,  'String',           {' ',' VOI label is not set yet (info)',' ',                    ...
                                ' VOI label may be set when no VOI is on display',' ',          ...
                                ' Started a VOI? Here''s the trick:',                           ...
                                '  1. Hide it using ''stOver'' GUI (VOI in memory)',            ...
                                '  2. Set the VOI label (Hit ''Start a VOI'' GUI ',             ...
                                '     and follow instructions)',                                ...
                                '  3. Then, hit ''h'' key to recover the VOI'});
elseif i1==4;
    set(h,  'String',           {' ','No VOIs to save. (info)',' ',                             ...
                                ' Hit ''Exit'' to close this session.'});
elseif i1==5;                   
    set(h,  'String',           {' ',' active VOI present (unable to save)',' ',               	...
                                ' Complete it or erase it (stOver)'});
elseif i1==6;
    set(h,  'String',           {' ',' no chages detected in this session (no need to save)',' '});

end;    
set(h,  'FontName','Courier new');
return;
%%


function                        local_sdv(h,i2)
%%
if ischar(i2);
    i1                          = umo_cstrs(char('urmri','pc','done'),lower(i2),'im1');
    if ~i1;                     i1                          = 1;                                    end;
else;                           i1                          = i2;                                   end;
if isempty(i1);                 ud                          = get(h,    'UserData');
    if isempty(ud);             i1                          = 1;
    else;                       i1                          = ud + 1;                       end;    end;
imax                            = 3;
if i1>imax;                     i1                          = 1;                                    end;
sss                             = ['(upright MRI: ',int2str(i1),'/',int2str(imax),')'];
%
if i1==1;
    set(h,  'String',           {' ',[' Consolidating upright MRI ',sss],' ',                   ...
                                '  Aim: To displace the images as upright as possible',         ...
                                '   1) AC at the crosshairs of white lines',                    ...
                                '   2) horizontal AC-PC plane (through top-AC & mid-PC)',       ...
                                '   3) vertical mid-plane (at least from AC to PC)',            ...
                                ' ', '  Two ways to displace the images: ',                 	...
                                '   Use GUIs under axial, coronal, and sagittal GUIs',          ...
                                '    cw: clockwise; cc: counter-clockwise',                     ...
                                '    dn: downward; up: upward; </> to your left/right',        	...
                                '   Hit (click right mouse button) on one image to rotate',     ...
                                '    the image by the angle when roate GUI of the view is hit', ...
                                '    (x=hit point will align with the nearest white line)',' ', ...
                                '  Hit Info GUI for more'});
elseif i1==2;
	set(h,  'String',           {' ',' When above three criteria are met, it is time to ',     	...
                                ['  record the posterior commissure point ',sss],' ',           ...
                                '  1) remove white lines using wLines GUI',                     ...
                                '  2) Hit left mouse button at PC. New lines appear at PC',     ...
                                '     Show/hide the lines with ''Line'' GUI to check if',       ...
                                '     PC is at the right location.',                            ...
                                '     If it looks OK, hit ''record PC'' GUI ',                  ...
                                '     It turns to ''PC done!'' if it looks OK (by calculation)',...
                                '     othewise, improvement suggestions will be displayed',     ...
                                '  ',' When PC is done, hit Approve GUI (you are done)',       	...
                                '  No revisions will be allowed once this session is closed.',  ...
                                '  Thus, make sure the MRI is upright in this session',         ...
                                '  If needed, hit the GUI and work further (repeatable)'});
else;
	set(h,  'String',           {' ',[' Additional information ',sss],' ',                    	...
                                ' The white lines are usable for checking the goal criteria',  	...
                                '  only when ''correct'' orthognal images are displayed',       ...
                                ' ',' Hit ''show AC'' GUI to display the ''correct'' images',   ...
                                ' Hit ''Line'' GUI a few times to check if ''correct'' images', ...
                                '  images are on display or not (secondary lines are visible)', ...
                                ' ',' ''Save'' GUI may be used to save displaments thus far',   ...
                                '  to return to work further and approve at a later time'});     	end;
                            
if i1==imax;                    set(h,  'FontName','Courier new',       'UserData',0);   
else;                           set(h,  'FontName','Courier new',       'UserData',i1);             end;
set(findobj(gcf, 'Tag','BJ_Info'),  'Callback',[mfilename,'(''sdv'',[]);']);
return;
%%
    
function                        local_voimode(h,i2)
%%
imax                            = 3;
if ischar(i2);
    i1                          = umo_cstrs(char('nx','tx','nt'),lower(i2),'im1');
    if ~i1;                     i1                          = 1;                                    end;
else;                           i1                          = i2;                                   end;
if isempty(i1);                 ud                          = get(h,    'UserData');
    if isempty(ud);             i1                          = 1;
    else;                       i1                          = ud + 1;                       end;    end;
if i1>imax;                     i1                          = 1;                                    end;
sss                             = ['(VOIs: ',int2str(i1),'/',int2str(imax),')'];
%
if i1==1;
    set(h,  'String',           {' ',[' Node mode (Nx) ',sss],' ',                              ...
                                ' Purpose (active when Nx GUIis highlighted in green):',        ...
                                '  To include voxels within the traced area into the VOI',      ...
                                '  To add/remove any missing/unwanted pieces/voxels',' ',       ...
                                ' Procedures (active while Nx GUI is highlighted in green): ',  ...
                                '  1. Trace (depress Lt.M.But & drag) voxels to include',       ...
                                '     (No need to close; automatically close)',                 ...
                                '  2. Trace (depress Rt.M.But & drag) voxels to remove',        ...
                                '  3. Depress Md.M.But & drag to add one layer of voxels',      ...
                                '     (within thresholds) to the VOI along the path',           ...
                                '     Also, consider using NT mode for this purpose',           ...
                                '  4. Hit ''h'' key to toggle betwen before/after the change',  ...
                                '  5. Hit Cx or other VOI defining mode GUIs to calcel Nx mode'});
elseif i1==2;
    set(h,  'String',           {' ',[' Threshold mode (Tx) ',sss],' ',                         ...
                                ' Purpose:',     ...
                                '  To include between-threshold voxels to the VOI',' ',         ...
                                ' Procedures (active while Tx GUI is highlighted in green): ',  ...
                                '  1. Adjust high/low thresholds (under ''jet'') to show',      ...
                                '     the structure of interstis in color ',                    ...
                                '  2. Cut connections (depress Rt.M.But & drag)',               ...
                                '     to other structures, if any (white lines will appear)',   ...
                                '     Depress Md.M.But & drag to remove whie lines, if needed', ...
                                '  3. Click Lt.M.But within the structure of interest',         ...
                                '     to include between-threshold voxels to the VOI',          ...
                                '  4. Hit ''h'' key to toggle betwen before/after the change',  ...
                                '  5. Hit Cx or other VOI defining mode GUIs to calcel Tx mode'});
elseif i1==3;
    set(h,  'String',           {' ',[' Node + Threshold mode ',sss],' ',                       ...
                                ' Purpose :',       ...
                                '  To include between-threshold voxels or to remove',           ...
                                '  outside-threshold voxels within/from the traced area',' ',   ...
                                ' Procedures (active while NT GUI is highlighted in green)',    ...
                                '  1. Adjust high/low shresholds to show the structure of ',    ...
                                '     interest in color (under ''jet'' color)',                 ...
                                '  2. Trace (depress Lt.M.But. & drag) an area to include, or', ...
                                '     Trace (depress Rt.M.But. & drag) an area to remove',      ...
                                '     within-threshold or outside-threshold voxels',            ...
                                '  3. Hit ''h'' key to toggle current and one previous versons',...
                                '  4. Hit Cx or other VOI defining mode GUIs to calcel NT mode'});
end;
if i1==imax;                    set(h,  'FontName','Courier new',       'UserData',0);   
else;                           set(h,  'FontName','Courier new',       'UserData',i1);             end;
set(findobj(gcf, 'Tag','BJ_Info'),  'Callback',[mfilename,'(''voimode'',[]);']);
return;
%%

function                        local_gen(h, i2);
%%
imax                            = 11;
if ischar(i2);
    i1                          = umo_cstrs(char('nx','tx','nt'),lower(i2),'im1');
    if ~i1;                     i1                          = 1;                                    end;
else;                           i1                          = i2;                                   end;
if isempty(i1);                 ud                          = get(h,    'UserData');
    if isempty(ud);             i1                          = 1;
    else;                       i1                          = ud + 1;                       end;    end;
if i1>imax;                     i1                          = 1;                                    end;
sss                             = ['(general: ',int2str(i1),'/',int2str(imax),')'];
if i1==1;
    set(h,  'String',           {' ',[' Welcome to VOILand ',sss],' ',                      ...
                                ' VOILand is an image volume display tool',' ',             ...
                                ' Your left is subject''s left by default (neuroscience)',  ...
                                '  Toggle between ''L/L'' and ''L/R'' (radiology)',         ...
                                ' Click left mouse button (Lt.M.But) (=hit) on an image',   ...
                                '  to display orthogonal images at the point.',             ...
                                '  Images location indicating lines will be displayed.',    ...
                                '  ''Line'' GUI displays/hides image location lines.',      ...
                                ' Click middle/right MBut to show normalized (=Md.M.But)',  ...
                                '  or raw (=Rt.M.But) image values (un/down to erase)',     ...
                                ' Hit keys for image navigation .. ',                       ...
                                '  u/n  :  Move trans-axial image up/down',                 ...
                                '  i/m  :  Move coronal image toward inon/nasion ',         ...
                                '  k/l  :  Move sagittal image toward right/left ',         ...
                                ' Hit ''Zoom'' GUI to zoom in (up tp x5)/out. ',            ...
                                ' Need to recenter images after zooming in?',               ...
                                '  Hit an image & 2/4/6/8 keys to move it in directions',   ...
                                '  of arrows on these #s on the number key pad',            ...
                                ' To check current key functions >> vL2_IJs(''show'',[]);', ...
                                ' Click ''Info'' GUI for general information on VOILand.'});
elseif i1==2;
    set(h,  'String',           {' ',[' Color-map related functions ',sss],' ',             ...
                                ' Colormap bars are shown on 4/5-th rows of GUI matrix',    ...
                                ' To toggle between ''Gray'' and ''Jet'' color maps',       ...
                                '  hit the left most GUI just below the colormap bars',     ...
                                ' Min/Max GUIs shows current raw min/max values',           ...
                                ' To change min/max values for image display,'              ...
                                '  use respective sliders (note: arrows do not work)',      ...
                                ' See later sections for Thx, and tH/tL sliders (for VOIs)',...
                                ' Other ''General GUIs'':',                                 ...
                                '  reCent : Bring images to default centers, if recentered',...
                                '  Save   : To save VOIs to a VOI file',                    ...
                                '  Exit   : To close current VOILand session'});
elseif i1==3;
    set(h,  'String',           {' ',[' To define/refine VOIs ',sss],' ',                   ...
                                '  1. Select a VOI to work on: Hit ''Start a VOI'' GUI',    ... 
                                '   VOIID Utility module will pop up, if no VOIs yet',      ...
                                '   VOI Selectio module will pop up, if any recorded VOIs', ...
                                '  2. Select VOI defining mode (2nd row GUIs)',             ...
                                '    Nx : Node mode (=trace the outline manually)',         ...
                                '    Tx : Threshold mode (using low/high thresholds)',      ...
                                '    Tc : Tx with auto-connection capability',              ...
                                '    Lx : Line input mode (e.g., for sulci)',               ...
                                '    Cx : Cancel VOI mode (back to default mode)',          ...
                                '   (See later sections for individual functions)',         ...
                                '   vGUIs provides more VOI defining tools ',               ...
                                '  3. Define/refine the VOI, using techniques shown below', ...
                                '  4. Hit ''Done'' when done (Saving in memory alone)',     ...
                                '    Select a completion status (such as ''complete'')',    ...
                                '    No time to complete a VOI? Recoed it as ''pending''',  ...
                                ' Warning: ',                                               ...
                                '  In Step 4, the VOI is saved in memory alone.',           ...
                                '  Use ''Save'' GUI to save VOIs in a file'                 ...
                                '  ''Save'' can be repeated until the session is closed'});
elseif i1==4;                  
    set(h,  'String',           {' ',[' Using image color map GUIs ',sss],' ',              ...
                                ' Two color maps (gray/jet) are used in VOILand',           ...
                                '  Baseline/secondary (lower/upper) maps are displayed',    ...
                                '  (left=lowest/right=highest image values on maps)',       ...
                                '  Click on Gray/Jet GUI to swap color maps (toggles)',     ...
                                ' To change color maps window:',                            ...
                                '  Click on ''CM'' GUI to pop up a separate window',        ...
                                '  Additional information will be displayed',               ...
                                ' Using low/high thresholds (tL/tH):',                      ...
                                '  Purpose: ',                                              ...
                                '   To set tL/tH such that the structure of interest (SOI)',...
                                '   is shown in color for Tx and Tc VOI defining modes. ',  ...
                                '  Procedures:',                                            ...
                                '   1. Show images using the color map (Jet is on display)',...
                                '   2. Adjust tL/tH by dragging  or using arrows',          ...
                                '      until SOI is shown in color & the rests in gray',    ...
                                ' Hit ''CM'' GUI to change image display settings ',        ...
                                '  A separate GUI window will pop up'});
elseif i1==5;
    set(h,  'String',           {' ',[' Quick list of key functions ',sss],' ',             ...
                                ' Keyboard  settings:',                                     ...
                                '  u/n  :  Move trans-axial image up/down',                 ...
                                '  i/m  :  Move coronal image toward inon/nasion ',         ...
                                '  k/l  :  Move sagittal image toward right/left ',         ...
                                '  2/4/6/8 (See arrows on these #s on number key pad)',     ...
                                '          Move VOILand window toward arrow directions',    ...
                                '          Move images toward arrow directions (Zoom>1)',   ...
                                '          (Hint: Click on an image to move)',              ...
                                '  h    :  cancel/recove one previous change',              ...
                                '  t/v  :  Trim a VOI at high(=t)/low(=v) intensity side',  ...
                                '  d/c  :  Cancel/perform auto-connect/auto-fill mode',     ...
                                ' Default mouse button (MB) functions (When Cx is on)',     ...
                                '  LtMB :  Display images at clicked point with lines',     ...
                                '  MdMB :  Display real image value where clicked',         ...
                                '  RtMB :  Display image value (1-128) where clicked',      ...
                                '          (Hit u/n to remove lines and value-plots)',      ...
                                ' Click ''Info'' GUI for next info',                        ...
                                ' Leave the curser on a GUI to display tips'});
elseif i1==6;                  vL2_Cx(0);
elseif i1==7;                  vL2_Nx(0);
elseif i1==8;                  vL2_Tx(0);
elseif i1==9;                  vL2_Ti(0);
elseif i1==10;                 vL2_Lx(0);
elseif i1==11;                 vL2_modifyVOIs('info',double(gcf));                              	end;
if i1==11;                     val                             = 0;                                 end;
%
if i1==imax;                    set(h,  'FontName','Courier new',       'UserData',0);   
else;                           set(h,  'FontName','Courier new',       'UserData',i1);             end;
set(findobj(gcf, 'Tag','BJ_Info'),  'Callback',[mfilename,'(''gen'',[]);']);
return;
%%
