function    [mRT, ImRT, viR]    = m08_getmRT(i1,dnoval,refval,sme); 

% To recover reference tissue / plasma TACs
%       
%       usage:  [mRT, ImRT, viR]    = m08_getmRT('eza.fln',dataNo2use,refInfo,sme)
%       
% Input variables:
%   eza.fln     -   file of tissue TACs generated by <<getmAT>>
%   dataNo2use  -   data # in eza.fln to use    
%   refInfo     -   VOIIDNo of the reference region 
%                   or
%                   file name and columns to use for files of Ca(t) (=plasma TACs)
%                   refInfo.fln     = file of plasma TACs
%                   refInfo.clm     = column strings to recover
%                                     e.g., {'time','met.corr'}
%                   or,
%                   file name of the plasma TACs alone (non-structure)
%
%   sme         -   [start-, mid-, end-frame] time matrix   (n by 3)
% Output variables:
%   mRT         -   the TAC of the reference region or plasma (at mid-frame times)
%   ImRT        -   integral of mAT
%   viR         -   [VOIIDNo, row# in eza.fln or 0, volume or 0]
%
% (cL)2008    hkuwaba1@jhmi.edu 

margin                          = 4;
if nargin<margin;               help(mfilename);                                    return;         end;

mRT                             = [];
ImRT                            = [];
viR                             = [];

if ischar(refval);
    [idx, inm, iex]             = fileparts(refval);
    % outputs of fit_refTACs.m:
    if strcmpi(iex,'.mat');
        if exist(refval,'file');
            disp('.info: using separate reference tisse TAC');
            disp([' file: ',refval]);
            x                	= load(refval);
            mRT              	= x.fitted.eRT;
            ImRT              	= integralTRP(x.fitted.tim, x.fitted.eRT);
            viR                	= [x.fitted.vID, 0, 0];
        else;
            disp('.problem! unable to locate smoothed reference region TAC file');
           	disp([' sought: ',refval]);                                                             end;
     	return; 
    else;
        if exist(refval,'file');
            cptfln           	= refval;
            clear refval;
            refval.fln        	= cptfln;
            refval.clm         	= gei(cptfln,               'orientation'); 
            % to continue to the next section
        else;
            disp('.problem! unable to locate plasma TAC file');
           	disp([' sought: ',refval]);                                             return;         end;
                                                                                            end;    end;
%%
if isstruct(refval);
    if isfield(refval,'fln') && isfield(refval,'clm');
        cpt                     = getCaT(refval.fln,        'clm',refval.clm);
        if isempty(cpt);                                                            return;         end;
        cpetc                   = prepTRP(cpt,sme(:,[2,2,2]),[]);
        if isempty(cpetc);                                                          return;         end;
        mRT                     = cpetc.Ca(cpetc.ise(:,1),  1);
        ImRT                    = cpetc.ICa(cpetc.ise(:,1),  1);
        viR                     = [10000,0,0];                                                      end;
else;
    if ischar(refval);          refval                      = vnosets(refval);                      end;
        
    [ttt, mRT, viR]             = m08_getTACs(i1,           dnoval(1),refval(1));
    if isempty(mRT);                                                                return;         end;
    ImRT                        = integralTRP(sme(:,2),     mRT);                                   end;

return;
%%