function        out             = mv2_FS1st(i1,fbc);
%% generated by mv2_i2m on 21-Jan-2022 10:07:12
% source file: iv2_FS1st
% 
if isnumeric(i1);               feval(['local_f',intstr(i1(1),3)],fbc);
else;                           out                         = feval(['local_',i1],fbc);             end;
return;
%
function        out             = local_opt(fbc);
%% listing option strings of this i-file:
% 
% 
out                             = [
'pmp'];
return;
%% 
function        out             = local_fun(fbc);
%% returning step descriptions
% 
out{1}                          = 'generate scripts to run Freesurfer (FS)';
out{2}                          = 'reformat FS-derived MRI (.mgz > .nii)';
out{3}                          = 'define ACPC points on FS-derived MRI';
out{4}                          = 'crop FS outputs around the brain';
out{5}                          = 'plot left vs. right VOI volumes';
out{6}                          = 'review/approve gray matter segmentation of FS';
out{7}                          = 'correct FS81 VOIs, if needed (for local managers; MRI #1 of singleFS)';
out{8}                          = 'review status of FS VOI revisions (MRI #1 of singleFS)';
out{9}                          = 'review original GM outlines on MRI (MRI #1 of singleFS)';
return;
%% 
function        out             = local_fls(fbc);
%% List of input/output files:
% 
global g4iv2;
out                             = {
'mri\tmp.mri'
'mri\fs_submitted.txt'
'mri\tmp_aparc_aseg.nii'
'mri\mgz_done.txt'
'mri\mgz_bc0.nii'
'mri\mgz_bc0_osz.nii'
'ezr\mgz_bc0_osz.acpc'
'mri\mgz_bc1.nii'
'mri\fsbc_fs81.nii'
'mri\fsbc.nii'
'mri\fssz.nii'
'mri\fsbc_BOLs.xyz'
'mri\fsbc_fs81.ezr'
'mri\fsbc_fs45.ezr'
['ezr\',g4iv2.xxx(fbc(3)).pmp,'_m2m.mat']
'ezr\fsbc_BOLs_ok.txt'
'mri\fsbc_fs81_rev_ok.txt'
'mri\fsbc_BOLs_R0.xyz'};
%
return;
%% 
function        out             = local_fns(fbc);
%% [in/out, file#@process, process#, file#@ifile, taskID#]
% 
out                             = [
1    1    1    1  105
2    1    1    2  105
2    2    1    3  105
1   1   2   4  97
1   2   2   5  97
2   1   2   6  97
1    1    3    6  105
2    1    3    7  105
1   1   4   3  97
1   2   4   8  97
1   3   4   5  97
1   4   4   7  97
2   1   4   9  97
2   2   4  10  97
2   3   4  11  97
2   4   4  12  97
2   5   4  13  97
2   6   4  14  97
2   7   4  15  97
1    1    5   13  111
1   1   6  10  99
1   2   6  12  99
1   3   6  15  99
2   1   6  16  99
1    1    7   10  100
1    2    7   11  100
1    3    7    9  100
1    4    7   13  100
1    5    7   12  100
2    1    7   17  100
1    1    8   17  111
1    1    9   11  111
1    2    9   18  111];
return;
%% 
function                        local_f001(fbc);
%% command lines for step 1
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
iii{2}                          = fbc(1, 1:3);                                                               
mv2_run_FS('single_script',iii,ooo);                                                                         
return
%% 
function                        local_f002(fbc);
%% command lines for step 2
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
if fbc(3)>1;                                                                            return;         end; 
fs_cropMRIs(iii(2),'MRI',ooo,'mgz2nii');                                                                     
return
%% 
function                        local_f003(fbc);
%% command lines for step 3
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
v0                              = spm_vol(iii{1});                                                           
h                               = findobj(findobj(groot,'Tag','iv2L2W'), 'Tag','L2W_gUseR0');                
str                             = get(h,    'String');                                                       
bgc                             = get(h,    'BackgroundColor');                                              
set(h,  'String','Starting VOILand. Be patient ..', 'BackgroundColor',iv2_bgcs(11));                         
drawnow;                                                                                                     
vL2Land(iii{1}, 'fun','acpc',   'vfl',ooo{1},   'mnt',whichMonitor([]));                                     
set(h,  'String',str,   'BackgroundColor',bgc);                                                              
vL2_BJs('Zoom',1);                                                                                           
vL2_BJs('Zoom',1);                                                                                           
drawnow;                                                                                                     
global g4vL2;                                                                                                
g4vL2{double(gcf)}.exit_do      = ['figure(findobj(groot,''Tag'',''iv2L2W'')); ', ...                        
                            'set(gcf, ''CurrentObject'',findobj(gcf, ''String'',''Update'')); mv2_a2([]);']; 
return
%% 
function                        local_f004(fbc);
%% command lines for step 4
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
if fbc(3)>1;                                                                            return;         end; 
use_freeSurfer(831,iii,ooo);                                                                                 
if exist(ooo{2},'file');        mv2_w4MMcoreg('run',fbc(1, 1:3),ooo(2),ooo(7));                         end; 
return
%% 
function                        local_f005(fbc);
%% command lines for step 5
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_run_FS('plot_lr_voi_volumes',iii,fbc(1, 1:3));                                                           
return
%% 
function                        local_f006(fbc);
%% command lines for step 6
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
iii{end+1}                     	= 'FS';                                                                      
mv2_w4MMcoreg('ols',fbc,        iii,ooo);                                                                    
return
%% 
function                        local_f007(fbc);
%% command lines for step 7
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_run_FS('edit_vois',         iii,ooo);                                                                    
return
%% 
function                        local_f008(fbc);
%% command lines for step 8
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
[f1, g1]                        = makefarrays('mri','fsbc_fs81_rev_ok.txt', 'fbc',[1,0,1]);                  
disp('.current completion status of revised FS VIOs (1=completed; 0=not yet)');                              
dispCharArrays(1, char('Subjects: ',g4iv2.yyy.snm),2,char(' competion status (1=done)',int2str(g1)));        
return
%% 
function                        local_f009(fbc);
%% command lines for step 9
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
snOLs(iii{1}, iii{2});                                                                                       
snOLsBJs('mk',5);                                                                                            
fNo                             = double(gcf);                                                               
global g4vL2;                                                                                                
set(gcf,    'Colormap',gray(g4vL2{fNo}.cmd));                                                                
snOLsAJs('Save','off',  gcf);                                                                                
return
%% 
