function    out                 = mv2_set4FS1st(fun,fbc,iii,ooo); 
% To record/update progression of prepMPfsx.m (=iPack)  
%       
%       usage:      mv2_set4FS1st_UR('fun',fbc,iii,ooo);
%
%   fun -   use get_localFun.m (>> get_localFun('mv2_set4FS1st_UR');) to display
%           current local functions 
%
% (cL)2019    hkuwaba1@jhmi.edu 

out                             = [];
margin                          = 4;
if nargin<margin;               help(mfilename);                                    return;         end;
% disp(fun);
if nargout;                     out                         = feval(['local_',lower(fun)],fbc,iii,ooo);
else;                           feval(['local_',lower(fun)],fbc,iii,ooo);                           end;
return;
%%

function    vmo                 = local_vmo(fbc,iii,ooo);
%% returns sybolic file names of input/output/confirmation files in a structure array
global g4iv2;
dicom_flg                       = feval(g4iv2.yyy.lds,'mri',[]);
snu                             = g4iv2.xxx(1).snu;
% fs81
vmo(1)                          = struct('input_mri',fullfile('mri','tmp.mri'),     ...
                                    'mri_bc0',fullfile('mri','fssz.nii'),           ...
                                    'mri_bc1',fullfile('mri','fsbc.nii'),           ...
                                    'mri_flag','fs', 'mri_space',1,                 ...
                                    'fs_in',fullfile('mri','dcm',dicom_flg),        ...
                                    'fs_out',char(fullfile('mri','tmp_aparc_aseg.nii'),     ...
                                    fullfile('mri','mgz_bc1.nii'),                  ...
                                    fullfile('mri','mgz_bc0.nii')),                 ...
                                    'voi_mask',fullfile('mri','fsbc_fs81.nii'),     ...
                                    'vois_ezr',fullfile('mri','fsbc_fs81.ezr'),   	...
                                    'vois_usr',fullfile('ezr','fsbc_fs81.ezr'),     ...
                                    'voi_flag','fs81', 'voi_id','f81',              ...
                                    'brainOLs',fullfile('mri','fsbc_BOLs.xyz'),   	...
                                    'seg_ok',fullfile('ezr','fsbc_BOLs_ok.txt'),   'm2m_ok',' ');
% fs
vmo(2)                          = struct('input_mri',fullfile('mri','tmp.nii'),     ...
                                    'mri_bc0',fullfile('mri','fssz.nii'),           ...
                                    'mri_bc1',fullfile('mri','fsbc.nii'),           ...
                                    'mri_flag','fs', 'mri_space',1,                 ...
                                    'fs_in',fullfile('mri','dcm',dicom_flg),        ...
                                    'fs_out',vmo(1).fs_out,                         ...
                                    'voi_mask',fullfile('mri','fsbc_fs81.nii'),     ...
                                    'vois_ezr',fullfile('mri','fsbc_fs45.ezr'),     ...
                                    'vois_usr',fullfile('ezr','fsbc_fs45.ezr'),     ...
                                    'voi_flag','fs45', 'voi_id','f45',              ...
                                    'brainOLs',fullfile('mri','fsbc_BOLs.xyz'),     ...
                                    'seg_ok',fullfile('ezr','fsbc_BOLs_ok.txt'),   'm2m_ok',' ');
% spatial normlization (SPM-unified segmentation):
% if strcmpi(snu(1:2),'fs');      add                         = '_iGM';
% else;                           add                         = '';                                   end;
% tpm                             = s12_stdtpms(snu);
vmo(3)                          = struct('input_mri',fullfile('mri',['fsbc','.nii']),        	...
                                    'mri_bc0',fullfile('mri',['fsbc','_snU',snu,'.nii']),       ...
                                    'mri_bc1',' ', 'mri_flag','sned', 'mri_space',-1,          	...
                                    'fs_in',' ',  	'fs_out',' ',   'voi_mask',' ',            	...
                                    'vois_ezr',fullfile('mri',['fsbc','_snU',snu,'_def.nii']),  ...
                                    'vois_usr',fullfile('mri',['fsbc','_snU',snu,'_inv.nii']),  ... 
                                    'voi_flag',' ', 'voi_id',' ', 'brainOLs',snu,               ...
                                    'seg_ok',fullfile('ezr',['fsbc','_snU',snu,'_ok.txt']),     ...
                                    'm2m_ok',' ');
return;
%%
