function        out             = mv2_doRTMs(i1,fbc);
%% generated by mv2_i2m on 23-May-2021 19:48:45
% source file: C:\tmp\tmp73829982552900.m
% 
if isnumeric(i1);               feval(['local_f',intstr(i1(1),3)],fbc);
else;                           out                         = feval(['local_',i1],fbc);             end;
return;
%
function        out             = local_opt(fbc);
%% listing option strings of this i-file:
% 
% 
out                             = [
'v4t'
'snu'
'ifc'
'ipj'
'pmp'
'eza'];
return;
%% 
function        out             = local_fun(fbc);
%% returning step descriptions
% 
out{1}                          = 'Complete/revise/review Analysis Sets (RTMs)';
out{2}                          = 'Perform reference tissue methods (RTMs)';
out{3}                          = 'display & plot RTM results';
out{4}                          = 'Select maps to generate (RTMs)';
out{5}                          = 'generate, spatially normalyze & smooth functional maps';
out{6}                          = 'view functional maps in MRI space';
out{7}                          = 'view spatially normalized & smoothed maps';
out{8}                          = 'display map completion status across subjects/scans';
return;
%% 
function        out             = local_fls(fbc);
%% List of input/output files:
% 
global g4iv2;
out                             = {
g4iv2.xxx(fbc(3)).v4t
['mpe/p4RTMs_',g4iv2.xxx(fbc(3)).eza,'.mat']
['mpe/r4RTMs_',g4iv2.xxx(fbc(3)).eza,'.mat']
['res/',g4iv2.xxx(fbc(3)).ifc,'_',g4iv2.xxx(fbc(3)).eza,'.eza']
['res/',g4iv2.xxx(fbc(3)).ifc,'_',g4iv2.xxx(fbc(3)).eza,'_ok.txt']
['res/',g4iv2.xxx(fbc(3)).ifc,'_',g4iv2.xxx(fbc(3)).eza,'_RTMs_done.m']
['mpe/',g4iv2.xxx(fbc(3)).snu,'_p4RTMs_',g4iv2.xxx(fbc(3)).eza,'_maps.mat']
['pet/',g4iv2.xxx(fbc(3)).ifc,'.ezm']
['ezr/',g4iv2.xxx(fbc(3)).ipj,'_',g4iv2.xxx(fbc(3)).ifc,'_',g4iv2.xxx(fbc(3)).pmp,'_p2m.mat']
['ezr/',g4iv2.xxx(fbc(3)).pmp,'_m2m.mat']
['res/',g4iv2.xxx(fbc(3)).snu,'_p4RTMs_',g4iv2.xxx(fbc(3)).eza,'_maps_done.m']
['mpe/',g4iv2.xxx(fbc(3)).snu,'_q4RTMs_',g4iv2.xxx(fbc(3)).eza,'_maps.mat']};
%
return;
%% 
function        out             = local_fns(fbc);
%% [in/out, file#@process, process#, file#@ifile, taskID#]
% 
out                             = [
1    1    1    1  109
2    1    1    2  109
2    2    1    3  109
1    1    2    4  115
1    2    2    5  115
1    3    2    3  115
2    1    2    6  115
1    1    3    3  111
1    1    4    3  100
2    1    4    7  100
1    1    5    8  115
1    2    5    4  115
1    3    5    7  115
1    4    5    5  115
1    5    5    9  115
1    6    5   10  115
2    1    5   11  115
2    2    5   12  115
1    1    6   12  111
1    2    6   11  111
1    1    7   12  111
1    2    7   11  111
1    1    8   12  111];
return;
%% 
function                        local_f001(fbc);
%% command lines for step 1
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_s2m('rtms',fbc(1),iii{1},   ooo);                      
return
%% 
function                        local_f002(fbc);
%% command lines for step 2
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_performRTMs(iii{1},iii{3},  ooo,fbc);                  
return
%% 
function                        local_f003(fbc);
%% command lines for step 3
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
x                               = load(iii{1});            
x.fbc                           = fbc(1,    1:3);          
x.job                           = 'disp_res';              
mv2_dispRes('set',x);                                      
return
%% 
function                        local_f004(fbc);
%% command lines for step 4
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_genMaps(iii,[fbc,1],ooo);                              
return
%% 
function                        local_f005(fbc);
%% command lines for step 5
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_genMaps(iii,[fbc,2],ooo);                              
return
%% 
function                        local_f006(fbc);
%% command lines for step 6
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_genMaps(iii,[fbc,3],[]);                               
return
%% 
function                        local_f007(fbc);
%% command lines for step 7
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_genMaps(iii,[fbc,4],[]);                               
return
%% 
function                        local_f008(fbc);
%% command lines for step 8
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_genMaps(iii,[fbc,11],ooo);                             
return
%% 
