function        out             = mv2_SN_fMaps_FSe1_(i1,fbc);
%% generated by mv2_i2m on 04-Jun-2021 08:09:42
% source file: C:\tmp\tmp73831134007428.m
% 
if isnumeric(i1);               feval(['local_f',intstr(i1(1),3)],fbc);
else;                           out                         = feval(['local_',i1],fbc);             end;
return;
%
function        out             = local_opt(fbc);
%% listing option strings of this i-file:
% 
% 
out                             = [];
function        out             = local_fun(fbc);
%% returning step descriptions
% 
out{1}                          = 'spatially normalize MRIs (ver.FS-TPM)';
out{2}                          = 'review/approve spatial normalization of MRI #1 (FS-TPM)';
return;
%% 
function        out             = local_fls(fbc);
%% List of input/output files:
% 
out                             = {
'mri\fsbc.nii'
'mri\fsbc_snUFSe1.nii'
'ezr\fsbc_snUFSe1_ok.tx'};
%
return;
%% 
function        out             = local_fns(fbc);
%% [in/out, file#@process, process#, file#@ifile, taskID#]
% 
out                             = [
1    1    1    1  115
2    1    1    2  115
1   1   2   2  99
2   1   2   3  99];
return;
%% 
function                        local_f001(fbc);
%% command lines for step 1
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
if fbc(3)~=1;                                                                       return;         end;
iii{end+1}                      = fbc(1, 1:3);                                                          
s12_run_snU('run_multi',iii,ooo);                                                                       
return
%% 
function                        local_f002(fbc);
%% command lines for step 2
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
tpm                             = s12_stdtpms(g4iv2.xxx(1).snu);                                        
iii{2}                          = tpm.xyz;                                                              
iii{3}                          = g4iv2.xxx(1).snu;                                                     
iii{4}                          = 'a';                                                                  
mv2_w4MMcoreg('oLs',fbc(1, 1:3),iii,ooo);                                                               
return
%% 
