function        out             = mv2_FS1st_rev(i1,fbc);
%% generated by mv2_i2m on 23-May-2022 19:19:57
% source file: iv2_FS1st_rev
% 
if isnumeric(i1);               feval(['local_f',intstr(i1(1),3)],fbc);
else;                           out                         = feval(['local_',i1],fbc);             end;
return;
%
function        out             = local_opt(fbc);
%% listing option strings of this i-file:
% 
% 
out                             = [
'pmp'];
return;
%% 
function        out             = local_fun(fbc);
%% returning step descriptions
% 
out{1}                          = 'correct FS81 VOIs, if needed (for local managers; MRI #1 of singleFS)';
out{2}                          = 'review status of FS VOI revisions (MRI #1 of singleFS)';
out{3}                          = 'display status of ''revised'' MRIs';
out{4}                          = 'reformat FS-derived MRI (.mgz > .nii; ver.rGM)';
out{5}                          = 'define ACPC points on FS-derived MRI (ver.rGM)';
out{6}                          = 'crop FS outputs around the brain (ver.rGM)';
out{7}                          = 'plot left vs. right VOI volumes (ver.rGM)';
out{8}                          = 'review/approve gray matter segmentation of FS (ver.rGM)';
out{9}                          = 'reformat FS-derived MRI (.mgz > .nii; ver.tLH)';
out{10}                         = 'define ACPC points on FS-derived MRI (ver.tLH)';
out{11}                         = 'crop FS outputs around the brain (ver.tLH)';
out{12}                         = 'plot left vs. right VOI volumes (ver.tLH)';
out{13}                         = 'review/approve gray matter segmentation of FS (ver.tLH)';
return;
%% 
function        out             = local_fls(fbc);
%% List of input/output files:
% 
global g4iv2;
out                             = {
'mri\fsbc.nii'
'mri\fssz.nii'
'mri\fsbc_fs81.nii'
'mri\fsbc_fs81.ezr'
'mri\fsbc_BOLs.xyz'
'mri\fsbc_BOLs_ok.txt'
'mri\fsbc_fs81_rev_ok.txt'
'mri\fssz_rGM_mgz_done.txt'
'mri\fssz_rGM_mgz_bc0.nii'
'mri\fssz_rGM_mgz_bc0_osz.nii'
'ezr\fssz_rGM_mgz_bc0_osz.acpc'
'mri\fssz_rGM_mgz_aparc_aseg.nii'
'mri\fssz_rGM_mgz_bc1.nii'
'mri\fssz_rGM_fs81.nii'
'mri\fssz_rGM_bc1.nii'
'mri\fssz_rGM_bc0.nii'
'mri\fssz_rGM_BOLs.xyz'
'mri\fssz_rGM_fs81.ezr'
'mri\fssz_rGM_fs45.ezr'
['ezr\',g4iv2.xxx(fbc(3)).pmp,'_m2m_rGM.mat']
'ezr\fssz_rGM_BOLs_ok.txt'
'mri\fssz_tLH_mgz_done.txt'
'mri\fssz_tLH_mgz_bc0.nii'
'mri\fssz_tLH_mgz_bc0_osz.nii'
'ezr\fssz_tLH_mgz_bc0_osz.acpc'
'mri\fssz_tLH_mgz_aparc_aseg.nii'
'mri\fssz_tLH_mgz_bc1.nii'
'mri\fssz_tLH_fs81.nii'
'mri\fssz_tLH_bc1.nii'
'mri\fssz_tLH_bc0.nii'
'mri\fssz_tLH_BOLs.xyz'
'mri\fssz_tLH_fs81.ezr'
'mri\fssz_tLH_fs45.ezr'
['ezr\',g4iv2.xxx(fbc(3)).pmp,'_m2m_tLH.mat']
'ezr\fssz_tLH_BOLs_ok.txt'};
%
return;
%% 
function        out             = local_fns(fbc);
%% [in/out, file#@process, process#, file#@ifile, taskID#]
% 
out                             = [
1    1    1    1  100
1    2    1    2  100
1    3    1    3  100
1    4    1    4  100
1    5    1    5  100
2    1    1    6  100
1    1    2    7  111
1    1    3    2  111
1   1   4   8  97
1   2   4   9  97
2   1   4  10  97
1    1    5   10  105
2    1    5   11  105
1   1   6  12  97
1   2   6  13  97
1   3   6   9  97
1   4   6  11  97
2   1   6  14  97
2   2   6  15  97
2   3   6  16  97
2   4   6  17  97
2   5   6  18  97
2   6   6  19  97
2   7   6  20  97
1    1    7   18  111
1   1   8  15  99
1   2   8  17  99
1   3   8  20  99
2   1   8  21  99
1   1   9  22  97
1   2   9  23  97
2   1   9  24  97
1    1   10   24  105
2    1   10   25  105
1   1  11  26  97
1   2  11  27  97
1   3  11  23  97
1   4  11  25  97
2   1  11  28  97
2   2  11  29  97
2   3  11  30  97
2   4  11  31  97
2   5  11  32  97
2   6  11  33  97
2   7  11  34  97
1    1   12   32  111
1   1  13  29  99
1   2  13  31  99
1   3  13  34  99
2   1  13  35  99];
return;
%% 
function                        local_f001(fbc);
%% command lines for step 1
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_run_FS('edit_vois',         iii,ooo);                                                                    
return
%% 
function                        local_f002(fbc);
%% command lines for step 2
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
[f1, g1]                        = makefarrays('mri','fsbc_fs81_rev_ok.txt', 'fbc',[1,0,1]);                  
disp('.current completion status of revised FS VIOs (1=completed; 0=not yet)');                              
dispCharArrays(1, char('Subjects: ',g4iv2.yyy.snm),2,char(' competion status (1=done)',int2str(g1)));        
return
%% 
function                        local_f003(fbc);
%% command lines for step 3
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
[idx, inm]                      = fileparts(iii{1});                                                         
disp(['.status of ''revised'' MRIs for Subject: ',      ...                                                  
                                deblank(g4iv2.yyy.snm(fbc(2), :)),'(MRI # 1 of singleFS)']);                 
ss3                             = {'_rGM.mat',  '_tLH.mat', '_rHx.mat'};                                     
st3                             = {' Approach 1 (rGM):', ' Approach 2 (tLH):', ' historical versions:'};     
for i=1:1:3;                                                                                                 
    if exist(fullfile(idx, [inm,ss3{i}]),'file');                                                            
      	disp(st3{i});                                                                                         
        if i<3;                                                                                              
            x               	= load(fullfile(idx, [inm,ss3{i}]));                                            
          	disp(x);                                                                                          
          	if exist(fullfile(idx, [inm,ss3{i}(1, 1:4),'_mgz_done.txt']),'file');                             
                disp(' > Freesurfer - done');                                                                
            else;                                                                                            
                disp(' > Freesurfer not completed yet');                                            end;     
        else;                                                                                                
            load(fullfile(idx, [inm,ss3{i}]));                                                               
            for j=1:1:numel(rHx);                           disp(rHx(j));   end;    end;    end;    end;     
fs                              = feval(g4iv2.yyy.lds, 'fsd',g4iv2.yyy.usr);                                 
ss                              = dir(fullfile(fs.fs.home, [char(42),'_',inm,'_',char(42),'.sh']));          
if isempty(ss);                 disp(' > no scripts for this subject/mri');                                  
else;                           disp(' > existing scripts for Freesurfer');                                  
                                dispCharArrays(1,char(ss.name));                                    end;     
return
%% 
function                        local_f004(fbc);
%% command lines for step 4
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
if fbc(3)>1;                                                                            return;         end; 
fs_cropMRIs(iii(2),'MRI',ooo,'mgz2nii');                                                                     
return
%% 
function                        local_f005(fbc);
%% command lines for step 5
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
v0                              = spm_vol(iii{1});                                                           
h                               = findobj(findobj(groot,'Tag','iv2L2W'), 'Tag','L2W_gUseR0');                
str                             = get(h,    'String');                                                       
bgc                             = get(h,    'BackgroundColor');                                              
set(h,  'String','Starting VOILand. Be patient ..', 'BackgroundColor',iv2_bgcs(11));                         
drawnow;                                                                                                     
vL2Land(iii{1}, 'fun','acpc',   'vfl',ooo{1},   'mnt',whichMonitor([]));                                     
set(h,  'String',str,   'BackgroundColor',bgc);                                                              
vL2_BJs('Zoom',1);                                                                                           
vL2_BJs('Zoom',1);                                                                                           
drawnow;                                                                                                     
global g4vL2;                                                                                                
g4vL2{double(gcf)}.exit_do      = ['figure(findobj(groot,''Tag'',''iv2L2W'')); ', ...                        
                            'set(gcf, ''CurrentObject'',findobj(gcf, ''String'',''Update'')); mv2_a2([]);']; 
return
%% 
function                        local_f006(fbc);
%% command lines for step 6
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
if fbc(3)>1;                                                                            return;         end; 
use_freeSurfer(831,iii,ooo);                                                                                 
if exist(ooo{2},'file');        mv2_w4MMcoreg('run',fbc(1, 1:3),ooo(2),ooo(7));                         end; 
return
%% 
function                        local_f007(fbc);
%% command lines for step 7
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_run_FS('plot_lr_voi_volumes',iii,fbc(1, 1:3));                                                           
return
%% 
function                        local_f008(fbc);
%% command lines for step 8
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
iii{end+1}                     	= 'fssz_rGM';                                                                
mv2_w4MMcoreg('ols',fbc,        iii,ooo);                                                                    
return
%% 
function                        local_f009(fbc);
%% command lines for step 9
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
if fbc(3)>1;                                                                            return;         end; 
fs_cropMRIs(iii(2),'MRI',ooo,'mgz2nii');                                                                     
return
%% 
function                        local_f010(fbc);
%% command lines for step 10
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
v0                              = spm_vol(iii{1});                                                           
h                               = findobj(findobj(groot,'Tag','iv2L2W'), 'Tag','L2W_gUseR0');                
str                             = get(h,    'String');                                                       
bgc                             = get(h,    'BackgroundColor');                                              
set(h,  'String','Starting VOILand. Be patient ..', 'BackgroundColor',iv2_bgcs(11));                         
drawnow;                                                                                                     
vL2Land(iii{1}, 'fun','acpc',   'vfl',ooo{1},   'mnt',whichMonitor([]));                                     
set(h,  'String',str,   'BackgroundColor',bgc);                                                              
vL2_BJs('Zoom',1);                                                                                           
vL2_BJs('Zoom',1);                                                                                           
drawnow;                                                                                                     
global g4vL2;                                                                                                
g4vL2{double(gcf)}.exit_do      = ['figure(findobj(groot,''Tag'',''iv2L2W'')); ', ...                        
                            'set(gcf, ''CurrentObject'',findobj(gcf, ''String'',''Update'')); mv2_a2([]);']; 
return
%% 
function                        local_f011(fbc);
%% command lines for step 11
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
if fbc(3)>1;                                                                            return;         end; 
use_freeSurfer(831,iii,ooo);                                                                                 
if exist(ooo{2},'file');        mv2_w4MMcoreg('run',fbc(1, 1:3),ooo(2),ooo(7));                         end; 
return
%% 
function                        local_f012(fbc);
%% command lines for step 12
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
mv2_run_FS('plot_lr_voi_volumes',iii,fbc(1, 1:3));                                                           
return
%% 
function                        local_f013(fbc);
%% command lines for step 13
% 
global g4iv2;
% 
[iii, ooo]                      = mv2_genfln(fbc,   1);
% command lines start here: 
% 
iii{end+1}                     	= 'fssz_tLH';                                                                
mv2_w4MMcoreg('ols',fbc,        iii,ooo);                                                                    
return
%% 
