% Generated by mv2_sumRes_s0 (10-Nov-2022 16:49:17)
% See IDAE manual to know how to enter result summary sections
% Outputs are organized by sections (headed by $$$) and subsections
% (headed by #) under each section
% First, enter your section & subsection titles below

$$$ enter section title here
# enter subsection title here
% generated by: mv2_sumRes_s0 @10-Nov-2022 16:53:20
task    disp    ascendingx 
oset    vst$iv2
% data lines
% data #1
res tra_rsz_FS81_v9_taaa_BPIT_60T90_Cb.ezd  1 BP 
% 
% suggested make-up lines: 
% end of added section
