% Generated by mv2_sumRes_s0 (14-Oct-2022 20:24:19)
% See IDAE manual to know how to enter result summary sections
% Outputs are organized by sections (headed by $$$) and subsections
% (headed by #) under each section
% First, enter your section & subsection titles below
% suggested make-up lines:
% end of added section
$$$ VT
# VT_HIS
% generated by: mv2_sumRes_s0 @15-Oct-2022 10:19:00
task    disp    ascending1
oset    vst$iv2
% data lines
% data #1
res tra_rsz_FS81_v2_taaa_PRGA_20T90_noTAD.ezd  1 VT
% %
