% Generated by mv2_sumRes_s0 (10-Nov-2022 16:49:17)
% See IDAE manual to know how to enter result summary sections
% Outputs are organized by sections (headed by $$$) and subsections
% (headed by #) under each section
% First, enter your section & subsection titles below
$$$ SAVE PET1_BP_histogram
# SAVE DVR
% generated by: mv2_sumRes_s0 @31-Oct-2022 17:51:41
task    disp    ascending1
oset    vst$iv2
% data lines
% data #1
res tra_rsz_hmcMIT_FS81_v9_tbaa_BPIT_60T90_Cb.ezd  1 BP